import telebot
from telebot import types


bot = telebot.TeleBot('5874121609:AAGdJc88ZUHUr_JQPuiRdjIr1BuVhuPoQjg')


@bot.message_handler(commands=['start'])
def start(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    btn1 = types.KeyboardButton("Одежды для мужчин")
    btn2 = types.KeyboardButton("Одежды для женщин")
    btn3 = types.KeyboardButton("Одежды для детей")
    markup.add(btn1, btn2, btn3)
    bot.send_message(message.chat.id, text='Привет, {0.first_name}! Добро пожаловать в магазин одежд "Gergeona. Выберите категорию заказа ниже"'.format(message.from_user), reply_markup=markup)
    
@bot.message_handler(content_types=['text'])
def function(message):
    if(message.text == "Одежды для мужчин"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn1 = types.KeyboardButton("Вернуться в главное меню")
        markup.add(btn1)
        bot.send_message(message.chat.id, text = "Отдел: Мужские одежды", reply_markup = markup)
        keyboard=types.InlineKeyboardMarkup()
        key1=types.InlineKeyboardButton(text = 'Футболки', callback_data = 'footbolka')
        keyboard.add(key1)
        key2=types.InlineKeyboardButton(text = 'Толстовки', callback_data = 'tolstovki')
        keyboard.add(key2)
        key3=types.InlineKeyboardButton(text = 'Трико', callback_data = 'triko')
        keyboard.add(key3)
        key4=types.InlineKeyboardButton(text = 'Джинсы', callback_data = 'jinsy')
        keyboard.add(key4)
        key5=types.InlineKeyboardButton(text = 'Кепки', callback_data = 'kepka')
        keyboard.add(key5)
        key6=types.InlineKeyboardButton(text = 'Шапки', callback_data = 'shapka')
        keyboard.add(key6)
        key7=types.InlineKeyboardButton(text = 'Кроссовки', callback_data = 'krossovki')
        keyboard.add(key7)
        key8=types.InlineKeyboardButton(text = 'Ботинки', callback_data = 'botinki')
        keyboard.add(key8)
        bot.send_message(message.chat.id, text="Выберите виды одежды которые вы хотите заказать:", reply_markup=keyboard)

    elif(message.text == "Одежды для женщин"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btnn1 = types.KeyboardButton("Вернуться в главное меню")
        markup.add(btnn1)
        bot.send_message(message.chat.id, text = "Отдел: Женские одежды", reply_markup = markup)
        keyboard1=types.InlineKeyboardMarkup()
        key1=types.InlineKeyboardButton(text = 'Платья', callback_data = 'plate')
        keyboard1.add(key1)
        key2=types.InlineKeyboardButton(text = 'Кардиганы', callback_data = 'kardigany')
        keyboard1.add(key2)
        key3=types.InlineKeyboardButton(text = 'Джинсы', callback_data = 'jeans')
        keyboard1.add(key3)
        key4=types.InlineKeyboardButton(text = 'Юбки', callback_data = 'ubki')
        keyboard1.add(key4)
        key5=types.InlineKeyboardButton(text = 'Шарфы', callback_data = 'sharfy')
        keyboard1.add(key5)
        key6=types.InlineKeyboardButton(text = 'Шапки', callback_data = 'shapki')
        keyboard1.add(key6)
        key7=types.InlineKeyboardButton(text = 'Ботинки', callback_data = 'botinok')
        keyboard1.add(key7)
        key8=types.InlineKeyboardButton(text = 'Туфли', callback_data = 'tufli')
        keyboard1.add(key8)
        bot.send_message(message.chat.id, text="Выберите виды одежды которые вы хотите заказать:", reply_markup=keyboard1)

    elif(message.text == "Одежды для детей"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn1 = types.KeyboardButton("Для мальчиков")
        btn2 = types.KeyboardButton("Для девочек")
        btn3 = types.KeyboardButton ("Вернуться в главное меню")
        markup.add(btn1, btn2, btn3)
        bot.send_message(message.chat.id, text = "Отдел: Детские одежды", reply_markup = markup)
    elif(message.text == "Для мальчиков"):
        keyboard2=types.InlineKeyboardMarkup()
        key1=types.InlineKeyboardButton(text = 'Футболки', callback_data = 'fm')
        keyboard2.add(key1)
        key2=types.InlineKeyboardButton(text = 'Трико', callback_data = 'tm')
        keyboard2.add(key2)
        key3=types.InlineKeyboardButton(text = 'Кроссовки', callback_data = 'km')
        keyboard2.add(key3)
        bot.send_message(message.chat.id, text="Выберите виды одежды которые вы хотите заказать:", reply_markup=keyboard2)
    elif(message.text == "Для девочек"):
        keyboard3=types.InlineKeyboardMarkup()
        key1=types.InlineKeyboardButton(text = 'Футболки', callback_data = 'fd')
        keyboard3.add(key1)
        key2=types.InlineKeyboardButton(text = 'Трико', callback_data = 'td')
        keyboard3.add(key2)
        key3=types.InlineKeyboardButton(text = 'Кроссовки', callback_data = 'kd')
        keyboard3.add(key3)
        bot.send_message(message.chat.id, text="Выберите виды одежды которые вы хотите заказать:", reply_markup=keyboard3)
    elif(message.text == "Вернуться в главное меню"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn1 = types.KeyboardButton("Одежды для мужчин")
        btn2 = types.KeyboardButton("Одежды для женщин")
        btn3 = types.KeyboardButton("Одежды для детей")
        markup.add(btn1, btn2, btn3)
        bot.send_message(message.chat.id, text="Вы вернулись в главное меню", reply_markup=markup)

        @bot.callback_query_handler(func = lambda call: True)
        def answer(call):
            if message.chat.type == 'private':
                if call.data == 'tolstovki':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские толстовки", reply_markup = markup)
                    r = open("tolstovka.jpg", 'rb')
                    bot.send_photo(message.chat.id, r)
                    bot.send_message(call.message.chat.id, text = "Толстовки 'Field Marshal'. В наличии: 65\nДоступные размеры: 46, 48, 50", reply_markup=r)
                    r = open("tolstovka1.jpg", 'rb')
                    bot.send_photo(message.chat.id, r)
                    bot.send_message(call.message.chat.id, text = "Толстовки 'The North Face'. В наличии: 44\nДоступные размеры: 46, 50", reply_markup=r)
                    r = open("tolstovka2.jpg", 'rb')
                    bot.send_photo(message.chat.id, r)
                    bot.send_message(call.message.chat.id, text = "Толстовки 'Hersegovina'. В наличии: 46\nДоступные размеры: 46, 50", reply_markup=r)
                elif call.data == 'footbolka': 
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские футболки", reply_markup = markup)
                    e = open("tshirt.jpg", 'rb')
                    bot.send_photo(message.chat.id, e)
                    bot.send_message(call.message.chat.id, text = "Футболки с резинкой. В наличии: 53\nДоступные размеры: 44, 46, 50", reply_markup=e)
                    e = open("tshirt1.jpg", 'rb')
                    bot.send_photo(message.chat.id, e)
                    bot.send_message(call.message.chat.id, text = "Футболки свободные. В наличии: 64\nДоступные размеры: 46, 52, 48", reply_markup=e)
                    e = open("tshirt2.jpg", 'rb')
                    bot.send_photo(message.chat.id, e)
                    bot.send_message(call.message.chat.id, text = "Футболки с воротником. В наличии: 71\nДоступные размеры: 44, 48", reply_markup=e)
                elif call.data == 'jinsy':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские джинсы", reply_markup = markup)
                    w = open("jeans.jpg", 'rb')
                    bot.send_photo(message.chat.id, w)
                    bot.send_message(call.message.chat.id, text = "Джинсы классические синие. В наличии: 67\nДоступные размеры: 38, 42, 48", reply_markup=w)
                    w = open("jeans1.jpg", 'rb')
                    bot.send_photo(message.chat.id, w)
                    bot.send_message(call.message.chat.id, text = "Джинсы светло-синие. В наличии: 62\nДоступные размеры: 40, 44, 48", reply_markup=w)
                    w = open("jeans2.jpg", 'rb')
                    bot.send_photo(message.chat.id, w)
                    bot.send_message(call.message.chat.id, text = "Джинсы светлые. В наличии: 74\nДоступные размеры: 42, 44 ,48", reply_markup=w)
                elif call.data == 'triko':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские трико", reply_markup = markup)
                    q = open("triko.jpg", 'rb')
                    bot.send_photo(message.chat.id, q)
                    bot.send_message(call.message.chat.id, text = "Трико 'New Balance'. В наличии: 79\nДоступные размеры: 40, 42, 48", reply_markup=q)
                    q = open("triko1.jpg", 'rb')
                    bot.send_photo(message.chat.id, q)
                    bot.send_message(call.message.chat.id, text = "Трико 'Future'. В наличии: 94\nДоступные размеры: 46, 48", reply_markup=q)
                    q = open("triko2.jpg", 'rb')
                    bot.send_photo(message.chat.id, q)
                    bot.send_message(call.message.chat.id, text = "Трико 'Aquatic'. В наличии: 84\nДоступные размеры: 40, 44", reply_markup=q)
                elif call.data == 'kepka':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские кепки", reply_markup = markup)
                    u = open("cap.jpg", 'rb')
                    bot.send_photo(message.chat.id, u)
                    bot.send_message(call.message.chat.id, text = "Кепки 'RedFox'. В наличии: 102", reply_markup=u)
                    u = open("cap1.jpg", 'rb')
                    bot.send_photo(message.chat.id, u)
                    bot.send_message(call.message.chat.id, text = "Кепки 'Lonsdale'. В наличии: 98", reply_markup=u)
                    u = open("cap2.jpg", 'rb')
                    bot.send_photo(message.chat.id, u)
                    bot.send_message(call.message.chat.id, text = "Кепки 'Everlast'. В наличии: 93", reply_markup=u)
                elif call.data == 'shapka':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские шапки", reply_markup = markup)
                    i = open("shapka.jpg", 'rb')
                    bot.send_photo(message.chat.id, i)
                    bot.send_message(call.message.chat.id, text = "Шапки 'Song Ting'. В наличии: 85", reply_markup=i)
                    i = open("shapka1.jpg", 'rb')
                    bot.send_photo(message.chat.id, i)
                    bot.send_message(call.message.chat.id, text = "Шапки 'Black'. В наличии: 105", reply_markup=i)
                    i = open("shapka2.jpg", 'rb')
                    bot.send_photo(message.chat.id, i)
                    bot.send_message(call.message.chat.id, text = "Шапки 'LBV'. В наличии: 91", reply_markup=i)
                elif call.data == 'krossovki':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские кроссовки", reply_markup = markup)
                    p = open("krossy.jpg", 'rb')
                    bot.send_photo(message.chat.id, p)
                    bot.send_message(call.message.chat.id, text = "Кроссовки 'Louis'. В наличии: 36\nДоступные размеры: 39, 41, 42", reply_markup=p)
                    p = open("krossy1.jpg", 'rb')
                    bot.send_photo(message.chat.id, p)
                    bot.send_message(call.message.chat.id, text = "Кроссовки 'El Tempo'. В наличии: 41\nДоступные размеры: 37, 38, 39, 40", reply_markup=p)
                    p = open("krossy2.jpg", 'rb')
                    bot.send_photo(message.chat.id, p)
                    bot.send_message(call.message.chat.id, text = "Кроссовки 'Ecco'. В наличии: 30\nДоступные размеры: 39, 41", reply_markup=p)
                elif call.data == 'botinki':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Мужские ботинки", reply_markup = markup)
                    a = open("botinki.jpg", 'rb')
                    bot.send_photo(message.chat.id, a)
                    bot.send_message(call.message.chat.id, text = "Ботинки осенние. В наличии: 27\nДоступные размеры: 38, 39, 40", reply_markup=a)
                    a = open("botinki1.jpg", 'rb')
                    bot.send_photo(message.chat.id, a)
                    bot.send_message(call.message.chat.id, text = "Ботинки зимние. В наличии: 42\nДоступные размеры: 38, 40", reply_markup=a)
                    a = open("botinki2.jpg", 'rb')
                    bot.send_photo(message.chat.id, a)
                    bot.send_message(call.message.chat.id, text = "Ботинки-кроссовки. В наличии: 34\nДоступные размеры: 39, 40, 42", reply_markup=a)
                elif call.data == 'plate':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские платья", reply_markup = markup)
                    rr = open("plate.jpg", 'rb')
                    bot.send_photo(message.chat.id, rr)
                    bot.send_message(call.message.chat.id, text = "Платья прямые с пуговицой. В наличии: 47\nДоступные размеры: 42, 44, 48", reply_markup=rr)
                    rr = open("plate1.jpg", 'rb')
                    bot.send_photo(message.chat.id, rr)
                    bot.send_message(call.message.chat.id, text = "Платья прямые с обрезом. В наличии: 59\nДоступные размеры: все размеры", reply_markup=rr)
                    rr = open("plate2.jpg", 'rb')
                    bot.send_photo(message.chat.id, rr)
                    bot.send_message(call.message.chat.id, text = "Платья прямые классические. В наличии: 63\nДоступные размеры: все размеры", reply_markup=rr)
                elif call.data == 'kardigany': 
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские кардиганы", reply_markup = markup)
                    ee = open("kardigan.jpg", 'rb')
                    bot.send_photo(message.chat.id, ee)
                    bot.send_message(call.message.chat.id, text = "Кардиганы шерстяные. В наличии: 31\nДоступные размеры: 48, 50", reply_markup=ee)
                    ee = open("kardigan1.jpg", 'rb')
                    bot.send_photo(message.chat.id, ee)
                    bot.send_message(call.message.chat.id, text = "Кардиганы вязанные. В наличии: 27\nДоступные размеры: 48, 52", reply_markup=ee)
                    ee = open("kardigan2.jpg", 'rb')
                    bot.send_photo(message.chat.id, ee)
                    bot.send_message(call.message.chat.id, text = "Кардиганы вязанные короткие. В наличии:42\nДоступные размеры: 46, 48", reply_markup=ee)
                elif call.data == 'jinsy':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские джинсы", reply_markup = markup)
                    ww = open("jeans.jpg", 'rb')
                    bot.send_photo(message.chat.id, ww)
                    bot.send_message(call.message.chat.id, text = "Джинсы с разрезами. В наличии: 77\nДоступные размеры: 40, 44, 46, 50", reply_markup=ww)
                    ww = open("jeans1.jpg", 'rb')
                    bot.send_photo(message.chat.id, ww)
                    bot.send_message(call.message.chat.id, text = "Джинсы бойфренд. В наличии: 54\nДоступные размеры: 40, 48, 52", reply_markup=ww)
                    ww = open("jeans2.jpg", 'rb')
                    bot.send_photo(message.chat.id, ww)
                    bot.send_message(call.message.chat.id, text = "Джинсы серые классические. В наличии: 95\nДоступные размеры: все размеры", reply_markup=ww)
                elif call.data == 'ubki':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские юбки", reply_markup = markup)
                    qq = open("ubki.jpg", 'rb')
                    bot.send_photo(message.chat.id, qq)
                    bot.send_message(call.message.chat.id, text = "Юбки классические черные. В наличии: 101\nДоступные размеры: 40, 42, 44, 50", reply_markup=qq)
                    qq = open("ubki1.jpg", 'rb')
                    bot.send_photo(message.chat.id, qq)
                    bot.send_message(call.message.chat.id, text = "Юбки прямые. В наличии: 124\nДоступные размеры: все размеры", reply_markup=qq)
                    qq = open("ubki2.jpg", 'rb')
                    bot.send_photo(message.chat.id, qq)
                    bot.send_message(call.message.chat.id, text = "Юбки джинсовые. В наличии: 96\nДоступные размеры: 40, 48, 52", reply_markup=qq)
                elif call.data == 'sharfy':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские шарфы", reply_markup = markup)
                    uu = open("sharf.jpg", 'rb')
                    bot.send_photo(message.chat.id, uu)
                    bot.send_message(call.message.chat.id, text = "Шарфы шерстяные. В наличии: 74", reply_markup=uu)
                    uu = open("sharf1.jpg", 'rb')
                    bot.send_photo(message.chat.id, uu)
                    bot.send_message(call.message.chat.id, text = "Шарфы из кашемира. В наличии: 51", reply_markup=uu)
                    uu = open("sharf2.jpg", 'rb')
                    bot.send_photo(message.chat.id, uu)
                    bot.send_message(call.message.chat.id, text = "Шарфы из шелка. В наличии: 39", reply_markup=uu)
                elif call.data == 'shapki':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские шапки", reply_markup = markup)
                    ii = open("shapkaa.jpg", 'rb')
                    bot.send_photo(message.chat.id, ii)
                    bot.send_message(call.message.chat.id, text = "Шапки из меха. В наличии: 31", reply_markup=ii)
                    ii = open("shapkaa1.jpg", 'rb')
                    bot.send_photo(message.chat.id, ii)
                    bot.send_message(call.message.chat.id, text = "Шапки шерстяные. В наличии: 50", reply_markup=ii)
                    ii = open("shapkaa2.jpg", 'rb')
                    bot.send_photo(message.chat.id, ii)
                    bot.send_message(call.message.chat.id, text = "Шапки норковые. В наличии: 17", reply_markup=ii)
                elif call.data == 'botinok':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские ботинки", reply_markup = markup)
                    pp = open("botinok.jpg", 'rb')
                    bot.send_photo(message.chat.id, pp)
                    bot.send_message(call.message.chat.id, text = "Ботинки зимние. В наличии: 52\nДоступные размеры: 36, 37, 38, 39", reply_markup=pp)
                    pp = open("botinok1.jpg", 'rb')
                    bot.send_photo(message.chat.id, pp)
                    bot.send_message(call.message.chat.id, text = "Ботинки осенние. В наличии: 62\nДоступные размеры: 37, 38", reply_markup=pp)
                    pp = open("botinok2.png", 'rb')
                    bot.send_photo(message.chat.id, pp)
                    bot.send_message(call.message.chat.id, text = "Ботинки уги. В наличии: 46\nДоступные размеры: все размеры", reply_markup=pp)
                elif call.data == 'tufli':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Женские туфли", reply_markup = markup)
                    aa = open("tufli.jpg", 'rb')
                    bot.send_photo(message.chat.id, aa)
                    bot.send_message(call.message.chat.id, text = "Туфли замшевые. В наличии: 37\nДоступные размеры: 35, 36, 38", reply_markup=aa)                
                    aa = open("tufli1.jpg", 'rb')
                    bot.send_photo(message.chat.id, aa)
                    bot.send_message(call.message.chat.id, text = "Туфли классические с высоким каблуком. В наличии: 69\nДоступные размеры: все размеры", reply_markup=aa)
                    aa = open("tufli2.jpg", 'rb')
                    bot.send_photo(message.chat.id, aa)
                    bot.send_message(call.message.chat.id, text = "Туфли без каблука. В наличии: 73\nДоступные размеры: все размеры", reply_markup=aa)
                elif call.data == 'fm':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Футболки для мальчиков", reply_markup = markup)
                    aaa = open("footbolka.jpg", 'rb')
                    bot.send_photo(message.chat.id, aaa)
                    bot.send_message(call.message.chat.id, text = "Футболки с принтом. В наличии: 83\nДоступные размеры: 28, 30", reply_markup=aaa)
                elif call.data == 'tm':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Трико для мальчиков", reply_markup = markup)
                    d = open("trikoo.jpg", 'rb')
                    bot.send_photo(message.chat.id, d)
                    bot.send_message(call.message.chat.id, text = "Трико с начесом. В наличии: 43\nДоступные размеры: 28, 32", reply_markup=d)
                elif call.data == 'km':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Кроссовки для мальчиков", reply_markup = markup)
                    s = open("krossovki.jpg", 'rb')
                    bot.send_photo(message.chat.id, s)
                    bot.send_message(call.message.chat.id, text = "Кроссовки 'Angry Birds'. В наличии: 132\nДоступные размеры: 24, 25, 26, 27, 28, 29", reply_markup=s)
                elif call.data == 'fd':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Футболки для девочек", reply_markup = markup)
                    f = open("footbolka1.jpg", 'rb')
                    bot.send_photo(message.chat.id, f)
                    bot.send_message(call.message.chat.id, text = "Футболки с принтом. В наличии: 97\nДоступные размеры: 26, 28, 30, 32", reply_markup=f)
                elif call.data == 'td':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Трико для девочек", reply_markup = markup)
                    ff = open("trikoo1.png", 'rb')
                    bot.send_photo(message.chat.id, ff)
                    bot.send_message(call.message.chat.id, text = "Трико летние. В наличии: 61\nДоступные размеры: 24, 28, 30", reply_markup=ff)
                elif call.data == 'kd':
                    markup = types.ReplyKeyboardMarkup(resize_keyboard = True)
                    item1 = types.KeyboardButton("Вернуться в главное меню")
                    item2 = types.KeyboardButton("Заказать")
                    markup.add(item1, item2)
                    bot.send_message(message.chat.id, text = "Отдел: Кроссовки для девочек", reply_markup = markup)
                    h = open("krossovki1.jpg", 'rb')
                    bot.send_photo(message.chat.id, h)
                    bot.send_message(call.message.chat.id, text = "Кроссовки 'Rainbow'. В наличии: 48\nДоступные размеры: 23, 24, 25, 26, 27, 28", reply_markup=h)
                elif(message.text == "Вернуться в главное меню"):
                    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
                    btn1 = types.KeyboardButton("Одежды для мужчин")
                    btn2 = types.KeyboardButton("Одежды для женщин")
                    btn3 = types.KeyboardButton("Одежды для детей")
                    markup.add(btn1, btn2, btn3)
                    bot.send_message(message.chat.id, text="Вы вернулись в главное меню", reply_markup=markup)
                elif(message.text == "Заказать"):
                    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
                    btn1 = types.KeyboardButton("Visa")
                    btn2 = types.KeyboardButton("Kaspi Gold")
                    btn3 = types.KeyboardButton("Kaspi Red")
                    btn4 = types.KeyboardButton("Qiwi Кошелек")
                    btn5 = types.KeyboardButton("Отменить")
                    markup.add(btn1, btn2, btn3, btn4, btn5)
                    bot.send_message(message.chat.id, text="Выберите способ оплаты:", reply_markup = markup)
            

bot.polling(none_stop=True)